default:
  image: "node:20.11.1"

stages:
  - "test"

test:
  stage: "test"
  only:
    - "merge_requests"
    - "develop"
  script:
    - "npm clean-install"
    - "npm run expo:typed-routes"
    - 'echo "${CI_COMMIT_MESSAGE}" | npm run lint:commit'
    - "npm run lint:prettier"
    - "npm run lint:eslint"
    - "npm run lint:typescript"
    - "npm run test"
  artifacts:
    paths:
      - "coverage/"
    reports:
      coverage_report:
        coverage_format: "cobertura"
        path: "coverage/cobertura-coverage.xml"
      junit: "junit.xml"
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
