name: "ci"

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main, develop, staging]

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4.1.6"

      - name: "Setup Node.js"
        uses: "actions/setup-node@v4.0.2"
        with:
          node-version: "20.x"
          cache: "npm"

      - run: "npm clean-install"
      - run: "npm run expo:typed-routes"
      - run: 'npm run lint:commit -- --to "${{ github.sha }}"'
      - run: "npm run lint:prettier"
      - run: "npm run lint:eslint"
      - run: "npm run lint:typescript"
      - run: "npm run test"
